const employees = [
  {
    id: 1,
    parentId: "",
    name: "Brittney Johnson",
    PositionCode: "University Registrar",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "Boyd Building, 1011A",
    department: "",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    imageUrl: "https://randomuser.me/api/portraits/women/23.jpg",
  },
  {
    id: 2,
    parentId: "1",
    name: "Andy Kline",
    PositionCode: "Associate Registrar, Systems",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "Boyd Building, 1011B",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/11.jpg",
  },

  {
    id: 3,
    parentId: "1",
    name: "Esther Garcia Ramirez",
    PositionCode: "Associate Registrar, Academics",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "Boyd Building, 1011N",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    id: 4,
    parentId: "1",
    name: "Taylor Miller",
    PositionCode: "Adminstrative Assistant",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "Boyd Building, 1012A",
    department: "",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: 6,
    parentId: "2",
    name: "Micheal Green",
    PositionCode: "Sr Reporting Analyst",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "Boyd Building, 1011E",
    department: "Systems Analysts",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/7.jpg",
  },
  {
    id: 7,
    parentId: "2",
    name: "Margret Roberts",
    PositionCode: "Adminstrative Clerk",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "Boyd Building, 1011F",
    department: "Systems Analysts",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/women/6.jpg",
  },
  {
    id: 8,
    parentId: "2",
    name: "Selasi Ells",
    PositionCode: "Special Assistant",
    phone: "99887766",
    email: "employee@email.com",
    team: "",
    location: "Boyd Building, 1011G",
    department: "Systems Analysts",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    imageUrl: "https://randomuser.me/api/portraits/men/6.jpg",
  },
];

export default employees;
